#!/bin/sh

set -eu

if [ "$#" -ne 1 ]; then
  echo "usage: flutter_xcode_backend.sh <build|embed_and_thin>" >&2
  exit 2
fi

project_root="$(cd "$(dirname "$0")/../play-mobile" && pwd)"
environment_file="$project_root/ios/Flutter/flutter_export_environment.sh"

if [ -z "${FLUTTER_ROOT:-}" ] && [ -f "$environment_file" ]; then
  # Generated by flutter build ios --config-only in Xcode Cloud.
  . "$environment_file"
fi

if [ -z "${FLUTTER_ROOT:-}" ]; then
  flutter_version="${FLUTTER_VERSION:-3.44.9}"
  candidate="${HOME}/flutter-${flutter_version}"
  if [ -x "$candidate/bin/flutter" ]; then
    FLUTTER_ROOT="$candidate"
    export FLUTTER_ROOT
  fi
fi

if [ -z "${FLUTTER_ROOT:-}" ] || [ ! -f "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" ]; then
  echo "Flutter SDK not found. FLUTTER_ROOT=${FLUTTER_ROOT:-<unset>}" >&2
  exit 127
fi

exec /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" "$1"
